### ISSUE TITLE
questions about datas

### ISSUE THREAD

**Issue by Darkcast** [pwndoc/pwndoc#100]
ive have tried downloading json files from serveral places to import the vulnerabilities but I always get a msg saying that there something missing.can someone poing me out where i can get the appropiate files ?
thank you

**Comment by yeln4ts** [comment]
If you want to import external vulnerabilities, you would have to manually modify them to match the application format.
```
- references:
    - >-
      reference1
      reference2
  cvssv3: 'CVSS:3.0/AV:A/AC:H/PR:N/UI:R/S:U/C:H/I:L/A:N'
  cvssScore: '5.4'
  cvssSeverity: Medium
  details:
    - customFields: []
      locale: en
      title: Vuln Title
      vulnType: Internal Network
      description: >-
        <p>Description</p>
      observation: >-
        <p>Observation</p>
      remediation: >-
        <p>Remediation</p>
```
Serpico format is also handled, you could import directly: https://github.com/SerpicoProject/Serpico/blob/master/templates/template_findings.json
