### ISSUE TITLE
How to integrate with Bunkerweb ?

### ISSUE THREAD

**Issue by Sorrow81** [pwndoc/pwndoc#367]
Hello,

I am setting up my various services behind a reverse proxy. For that I use bunkerweb, this service works a bit like traefik.

I have an autoconf configuration and I try to run the reverse proxy on the frontend, but I get some errors. Do you have any advice on how to use pwndoc with [bunkerweb](https://docs.bunkerweb.io/1.4/) ?

<details>
  <summary>docker-composer.autoconf.yaml</summary>

```yaml
version: '3'

services:

  mybunker:
    image: bunkerity/bunkerweb:1.4.3
    ports:
      - 80:8080
      - 443:8443
    environment:
      - AUTOCONF_MODE=yes
      - MULTISITE=yes
      - SERVER_NAME=
      - API_WHITELIST_IP=127.0.0.0/8 10.20.30.0/24
      - USE_BAD_BEHAVIOR=no
    labels:
      - "bunkerweb.AUTOCONF"
    networks:
      - bw-autoconf
      - bw-services

  myautoconf:
    image: bunkerity/bunkerweb-autoconf:1.4.3
    volumes:
      - .:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - bw-autoconf

volumes:
  bw-data:

networks:
  bw-autoconf:
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
```
</details>

<details>
  <summary>docker-composer.pwndoc.yaml</summary>

```yaml
version: '3'

services:

  mongodb:
    image: mongo:4.2.15
    container_name: mongo-pwndoc
    volumes:
      - ./backend/mongo-data:/data/db
    restart: always
    environment:
      - MONGO_DB:pwndoc
    networks:
      - backend

  pwndoc-backend:
    build: ./backend
    image: yeln4ts/pwndoc:backend
    container_name: pwndoc-backend
    volumes:
      - ./backend/report-templates:/app/report-templates
      - ./backend/src/config:/app/src/config
    depends_on:
      - mongodb
    restart: always
    links:
      - mongodb
    networks: 
      - backend

  pwndoc-frontend:
    build: ./frontend
    image: yeln4ts/pwndoc:frontend
    container_name: pwndoc-frontend
    restart: always
    networks:
      backend:
      bw-services:
        aliases:
          - pwndoc
    labels:
      - bunkerweb.SERVER_NAME=pwndoc.site.localhost
      - bunkerweb.USE_REVERSE_PROXY=yes
      - bunkerweb.REVERSE_PROXY_URL=/
      - bunkerweb.REVERSE_PROXY_HOST=https://pwndoc:8443
      - bunkerweb.USE_CORS=no
      - bunkerweb.CORS_ALLOW_ORIGIN=*
     

volumes:
  mongo-data:

networks:
  backend:
      driver: bridge
  bw-services:
    external:
      name: bw-services
  ```
</details>

```yaml
...
  pwndoc-frontend:
    build: ./frontend
    image: yeln4ts/pwndoc:frontend
    container_name: pwndoc-frontend
    restart: always
    networks:
      backend:
      bw-services:
        aliases:
          - pwndoc
    labels:
      - bunkerweb.SERVER_NAME=pwndoc.site.localhost
      - bunkerweb.USE_REVERSE_PROXY=yes
      - bunkerweb.REVERSE_PROXY_URL=/
      - bunkerweb.REVERSE_PROXY_HOST=https://pwndoc:8443
      - bunkerweb.USE_CORS=no
      - bunkerweb.CORS_ALLOW_ORIGIN=*
...
```

![image](https://user-images.githubusercontent.com/43729314/192170951-cd0a6797-97ed-4238-a7d3-5127c2c8256c.png)

I think I need to make the dockerfile again to make it work with bunkerweb, is that right?

**Comment by Sorrow81** [comment]
After several tests, I downloaded the release rather than cloning the repo and it works. It was the utils lib that was not loaded and was causing errors.

I still get the CORS errors in the console.

**Comment by Sorrow81** [comment]
I found a solution. I removed the port in the socket.io call and increased the number of requests per second on that endpoint.

```js
import io from 'socket.io-client'
import {Loading} from 'quasar'
import { $t } from '@/boot/i18n'

export default ({ Vue }) => {
    // var socket = io(`${window.location.protocol}//${window.location.hostname}:${process.env.API_PORT}`);
    var socket = io(`${window.location.protocol}//${window.location.hostname}`);

    socket.on('disconnect', (error) => {
        Loading.show({
            message: `<i class='material-icons'>wifi_off</i><br /><p>${$t('msg.wrongContactingBackend')}</p>`, 
            spinner: null, 
            backgroundColor: 'red-10', 
            customClass: 'loading-error',
            delay: 5000
        })
    })
    socket.on('connect', () => {    
        Loading.hide()
    })

    Vue.prototype.$socket = socket
}  
```

And my docker-compose autoconf for bunkerweb.

```yaml
version: '3'
services:
  mongo-pwndoc:
    image: mongo:4.2.15
    container_name: mongo-pwndoc
    volumes:
      - ./backend/mongo-data:/data/db
    restart: always
    environment:
      - MONGO_DB:pwndoc
    networks: 
      bw-services:
        aliases:
          - mongo-pwndoc

  pwndoc-backend:
    build: ./backend
    image: yeln4ts/pwndoc:backend
    container_name: pwndoc-backend
    volumes:
      - ./backend/report-templates:/app/report-templates
      - ./backend/src/config:/app/src/config
    depends_on:
      - mongo-pwndoc
    restart: always
    links:
      - mongo-pwndoc
    networks: 
      bw-services:
        aliases:
          - pwndoc-backend

  pwndoc-frontend:
    build: ./frontend
    image: yeln4ts/pwndoc:frontend
    container_name: pwndoc-frontend
    restart: always
    networks:
      bw-services:
        aliases:
          - pwndoc-frontend
    labels:
      - bunkerweb.SERVER_NAME=pwndoc.site.localhost
      - bunkerweb.USE_REVERSE_PROXY=yes
      - bunkerweb.REVERSE_PROXY_WS=yes
      - bunkerweb.REVERSE_PROXY_URL=/
      - bunkerweb.REVERSE_PROXY_HOST=https://pwndoc-frontend:8443
      - bunkerweb.USE_BAD_BEHAVIOR=yes
      - bunkerweb.LIMIT_REQ_URL_1=/socket.io
      - bunkerweb.LIMIT_REQ_RATE_1=10r/s    
     

volumes:
  mongo-data:

networks:
  bw-services:
    external:
      name: bw-services

  ```
